"""Auto-generated from OpenGa_v3.3_Carbon.xlsx, then extended in V3 to match
OpenGa_v3.5_MEB.xlsx sections 29, 30 and 31. Do not hand-edit: regenerate."""
# key: (default, label, unit, section_row, status, confidence, source)
V33_DEFAULTS = {
    'CapProd':       (100000.0, 'Gallium production capacity', 'kg Ga/yr', 7, 'CITED', 'High',
        'Alcoa Wagerup gallium project design capacity: 100 metric tons per year (Alcoa press release 20 Oct 2025; US Dept of War USD174M equity announcement Sep 2026).'),
    'OpHours':       (8000.0, 'Operating hours', 'h/yr', 8, 'ASSUMPTION', 'Med',
        '91.3% availability. Engineering assumption for a continuous hydrometallurgical plant.'),
    'LIFE':          (30.0, 'Operating life', 'yr', 9, 'ASSUMPTION', 'Med',
        'Years 1-30 of operation; all capital deployed in Year 0. Standard TEA convention.'),
    'GaFeed':        (70.0, 'Gallium in spent Bayer liquor', 'mg/L', 14, 'PLACEHOLDER', 'Low',
        'Midpoint of the three LOW-TEMPERATURE refineries in the four-plant Bayer survey reported by ICSOBA 2023 (48, 53 and 85 mg/L; the fourth, a high-temperature refinery, ran 185 mg/L). Australian liquor has NOT been assayed. This is the single most important unknown in the model - see the Assay_Curve sheet.'),
    'VFeed':         (149.6, 'Vanadium in liquor', 'mg/L', 15, 'PLACEHOLDER', 'Low',
        'Jajarm plant characterisation (R7). PROXY - Australian V is unknown. V competes for resin capacity, so it inflates the resin inventory and therefore the column size.'),
    'AlFeed':        (50.0, 'Aluminium in liquor', 'g/L', 16, 'ASSUMPTION', 'Low',
        'Typical spent Bayer liquor supersaturation (R9). Drives Al carry-over to the precipitate.'),
    'LiqDensity':    (1.3, 'Liquor density', 'kg/L', 17, 'ASSUMPTION', 'Med',
        'Typical spent Bayer liquor, 1.25-1.35 (R9).'),
    'SSLoad':        (2.0, 'Suspended solids in liquor', 'kg/t liquor', 18, 'ASSUMPTION', 'Low',
        'Slipstream sampling estimate (R9).'),
    'ImpRatio':      (1.0, 'Impurity load ratio vs baseline', '-', 19, 'ASSUMPTION', 'Low',
        'Scales the CaO dose and purification cake. Use 1.0 if the impurity vector is unknown (R9).'),
    'FiltCakeMoist': (30.0, 'UP1  Filter cake moisture', '% w/w', 23, 'ASSUMPTION', 'Low',
        'Typical plate-and-frame cake moisture for a solids-polishing duty (R9). The Ga lost with this entrained liquor is DERIVED on the MEB, not assumed away.'),
    'WashRec':       (100.0, 'UP3  Ga retention through wash', '%', 28, 'ASSUMPTION', 'Low',
        'Displacement wash, no Ga loss assumed (R9).'),
    'EluEff':        (95.0, 'UP5  Elution efficiency', '%', 29, 'CITED', 'High',
        'Lu et al. 2017 (R2): 95% in 30 min with 4% w/w H2SO4.'),
    'PrecRec':       (100.0, 'UP7  Ga to precipitate', '%', 30, 'ASSUMPTION', 'Med',
        'Neutralisation to pH 6-8; Ga(OH)3 solubility neglected (R9).'),
    'CentRec':       (98.0, 'UP8  Ga recovery to cake', '%', 31, 'CITED', 'Med',
        'WP2 flowsheet (R6).'),
    'PurRec':        (95.0, 'UP9  Purification Ga recovery', '%', 32, 'ASSUMPTION', 'Low',
        'Engineering assumption (R9) - to be confirmed.'),
    'EWRec':         (95.0, 'UP10 Ga recovery to metal', '%', 33, 'ASSUMPTION', 'Med',
        'Per pass with electrolyte recycle (R9).'),
    'RefYield':      (97.0, 'UP11 Refining yield to 4N', '%', 34, 'CITED', 'Med',
        'WP2 flowsheet (R6).'),
    'WashBV':        (4.0, 'UP3  Wash water', 'bed volumes', 39, 'ASSUMPTION', 'Med',
        'Displacement wash, 3-5 BV (R6/R9). Tied to resin volume, not to a per-kg dose.'),
    'EluBV':         (3.0, 'UP5  Eluant volume', 'bed volumes', 40, 'ASSUMPTION', 'Med',
        'Typical acid elution 2-4 BV (R2/R9).'),
    'EluStrength':   (4.0, 'UP5  Eluant H2SO4 strength', '% w/w', 41, 'CITED', 'Med',
        'Lu et al. 2017 (R2).'),
    'AcidPurity':    (98.0, 'UP4  Delivered H2SO4 purity', '% w/w', 42, 'CITED', 'High',
        'Standard commercial grade (R1).'),
    'RegenBV':       (2.0, 'UP6  Regeneration water', 'bed volumes', 43, 'ASSUMPTION', 'Low',
        'Rinse to service (R9).'),
    'ResinLife':     (3.0, 'UP6  Resin service life', 'yr', 44, 'CITED', 'Med',
        '2-5 years, roughly 30 cycles (R6). Make-up is derived from inventory / life.'),
    'NaOHConc':      (32.0, 'UP7  NaOH solution strength', '% w/w', 45, 'CITED', 'Med',
        'Delivered as 32% w/w solution (R1).'),
    'NaOHTrim':      (0.0, 'UP7  NaOH pH trim beyond stoichiometric', 'kg/kg Ga', 46, 'ASSUMPTION', 'Low',
        'Liquor buffering capacity unknown; carried at zero (R9).'),
    'CakeMoist':     (40.0, 'UP8  Centrifuge cake moisture', '% w/w', 47, 'CITED', 'Med',
        'Hydroxide centrifuge cake (R6).'),
    'NaOH_UP9':      (3.9, 'UP9  Caustic dose', 'kg/kg Ga', 48, 'ASSUMPTION', 'Low',
        'MECHANISTIC basis: electrolyte make-up = volume x 120 g/L plus 1 mol NaOH per mol Ga. Luo et al. 2025 (R1) report a GROSS dose of 44.16 kg/kg, 11.4x higher. The v2.2 sodium ledger could not account for the difference (40.3 kg/kg unaccounted), which is why the mechanistic figure is the base case. The full range is carried in the tornado and the Monte Carlo.'),
    'CaODose':       (2.0, 'UP9  CaO dose', 'kg/kg Ga', 49, 'CITED', 'Med',
        'Luo et al. 2025 (R1), scaled by the impurity ratio.'),
    'HClDose':       (0.012, 'UP11 HCl dose', 'kg/kg Ga', 50, 'CITED', 'Med',
        'Luo et al. 2025 (R1). Minor line.'),
    'ElecGa':        (39.9, 'UP10 Electrolyte Ga concentration', 'g/L', 51, 'CITED', 'Med',
        'Xu et al. 2024 (R4).'),
    'ElecNaOH':      (120.0, 'UP10 Electrolyte NaOH concentration', 'g/L', 52, 'CITED', 'Med',
        'Xu et al. 2024 (R4).'),
    'ElecDens':      (1.15, 'UP10 Electrolyte density', 'kg/L', 53, 'ASSUMPTION', 'Low',
        'Engineering estimate (R9).'),
    'PumpHead':      (40.0, 'Liquor circuit total head', 'm', 57, 'ASSUMPTION', 'Low',
        'Slipstream take-off, filter press, IX bed pressure drop and return to circuit. Engineering assumption - confirm against the host refinery tie-in elevation.'),
    'WashHead':      (25.0, 'Wash / eluant / transfer circuit head', 'm', 58, 'ASSUMPTION', 'Low',
        'Engineering assumption.'),
    'PumpEff':       (70.0, 'Pump wire-to-water efficiency', '%', 59, 'ASSUMPTION', 'Med',
        'Typical centrifugal pump plus motor (R9).'),
    'EvapEcon':      (2.0, 'Evaporator economy', 'kg water / kg steam', 60, 'ASSUMPTION', 'Low',
        'Double effect. Single effect = 1.0, triple = ~2.7. Engineering assumption.'),
    'SteamLatent':   (2.26, 'Steam latent heat', 'MJ/kg', 61, 'CITED', 'High',
        'CRC / steam tables (R11).'),
    'EWVolt':        (2.4, 'Electrowinning cell voltage', 'V', 62, 'CITED', 'Med',
        'WP2 flowsheet (R6); range 2.1-2.4.'),
    'EWCE':          (47.9, 'Electrowinning current efficiency', '%', 63, 'CITED', 'Med',
        'WP2 flowsheet (R6). Reported range 47.9-99%; the dominant electrowinning energy lever.'),
    'MiscElec':      (15.0, 'Ancillary electricity allowance', '% of computed', 64, 'ASSUMPTION', 'Low',
        'Agitation, instrumentation, lighting, HVAC, conveying and small drives not separately modelled. Engineering allowance.'),
    'MGa':           (69.723, 'M(Ga)', 'g/mol', 68, 'CITED', 'High',
        'CRC physical constants (R11).'),
    'MNaOH':         (39.997, 'M(NaOH)', 'g/mol', 69, 'CITED', 'High',
        'CRC physical constants (R11).'),
    'MH2SO4':        (98.079, 'M(H2SO4)', 'g/mol', 70, 'CITED', 'High',
        'CRC physical constants (R11).'),
    'MNa2SO4':       (142.043, 'M(Na2SO4)', 'g/mol', 71, 'CITED', 'High',
        'CRC physical constants (R11).'),
    'MAl':           (26.982, 'M(Al)', 'g/mol', 72, 'CITED', 'High',
        'CRC physical constants (R11).'),
    'MOH':           (17.008, 'M(OH)', 'g/mol', 73, 'CITED', 'High',
        'CRC physical constants (R11).'),
    'MH2O':          (18.015, 'M(H2O)', 'g/mol', 74, 'CITED', 'High',
        'CRC physical constants (R11).'),
    'FarC':          (96485.0, 'Faraday constant', 'C/mol', 75, 'CITED', 'High',
        'CRC physical constants (R11).'),
    'GRAV':          (9.80665, 'Standard gravity', 'm/s2', 76, 'CITED', 'High',
        'CRC physical constants (R11).'),
    'EluDens':       (1.025, 'Density of 4% w/w H2SO4 eluant', 'kg/L', 77, 'CITED', 'High',
        'Standard solution density at 25 C (R11).'),
    'AcidDens':      (1.84, 'Density of 98% w/w H2SO4', 'kg/L', 78, 'CITED', 'High',
        'Standard solution density at 25 C (R11).'),
    'NaOHDens':      (1.35, 'Density of 32% w/w NaOH', 'kg/L', 79, 'CITED', 'High',
        'Standard solution density at 25 C (R11).'),
    'IXVel':         (20.0, 'IX superficial velocity', 'm/h', 84, 'ASSUMPTION', 'Low',
        'Fixed-bed ion exchange, typical design 10-25 m/h. Engineering assumption - confirm with the resin vendor. THIS, not resin capacity, is what sets the column diameter at these liquor flows.'),
    'IXBed':         (2.0, 'IX bed depth', 'm', 85, 'ASSUMPTION', 'Low',
        'Typical 1.5-3.0 m fixed bed (R9).'),
    'IXColLoad':     (2.0, 'IX columns in loading duty', '-', 86, 'ASSUMPTION', 'Med',
        'Lead-lag pair.'),
    'IXColTot':      (4.0, 'IX columns installed (total)', '-', 87, 'ASSUMPTION', 'Med',
        'Two loading, one on wash/elution/regeneration, one standby.'),
    'ResinBulk':     (0.72, 'Resin wet bulk density', 'kg/L', 88, 'ASSUMPTION', 'Low',
        'Typical chelating polystyrenic resin (R9).'),
    'FiltFlux':      (1.5, 'Filter press filtration flux', 'm3 liquor / m2 / h', 89, 'ASSUMPTION', 'Low',
        'Solids-polishing duty, engineering assumption (R9).'),
    'ReactRes':      (1.5, 'Precipitation reactor residence time', 'h', 90, 'ASSUMPTION', 'Low',
        'Neutralisation and crystal growth (R9).'),
    'VesFill':       (0.8, 'Vessel working volume fraction', '-', 91, 'ASSUMPTION', 'Med',
        'Freeboard allowance (R9).'),
    'TankDays':      (7.0, 'Reagent and product storage', 'days', 92, 'ASSUMPTION', 'Med',
        'One week of consumption (R9).'),
    'EvapU':         (1200.0, 'Evaporator overall heat transfer coefficient', 'W/m2.K', 93, 'ASSUMPTION', 'Low',
        'Forced-circulation evaporator on a caustic liquor (R9).'),
    'EvapDT':        (15.0, 'Evaporator effective temperature difference', 'K', 94, 'ASSUMPTION', 'Low',
        'Per effect (R9).'),
    'CentCap':       (5.0, 'Centrifuge hydraulic capacity per unit', 'm3/h', 95, 'ASSUMPTION', 'Low',
        'Disc-stack / decanter duty (R9).'),
    'EWRes':         (4.0, 'Electrowinning electrolyte residence time', 'h', 96, 'ASSUMPTION', 'Low',
        'Sets the cell-house tankage (R9).'),
    'EWRectCost':    (1500.0, 'Electrowinning rectifier cost', 'AUD/kW installed', 97, 'PLACEHOLDER', 'Low',
        'NO published correlation exists for gallium electrowinning rectifiers in Towler & Sinnott. Order-of-magnitude figure for a small DC rectifier set. VENDOR QUOTE REQUIRED - but at roughly 75 kW this is a trivial share of capital, so the exposure is small.'),
    'SparePct':      (30.0, 'Installed spares allowance', '% of pump cost', 98, 'ASSUMPTION', 'Med',
        'One spare per duty pump on critical services (R9).'),
    'VesThk':        (10.0, 'Vessel and tank shell thickness', 'mm', 99, 'ASSUMPTION', 'Low',
        'Nominal plate thickness for a low-pressure atmospheric vessel. Engineering assumption; a pressure design would need a code calculation.'),
    'SteelDens':     (7850.0, 'Steel density', 'kg/m3', 100, 'CITED', 'High',
        'Standard structural / vessel steel (R11).'),
    'HeadAllow':     (1.2, 'Vessel heads and internals allowance', '-', 101, 'ASSUMPTION', 'Low',
        'Shell mass multiplier covering heads, nozzles, supports and internals. Engineering assumption.'),
    'CentDia':       (0.4, 'Centrifuge bowl diameter', 'm', 102, 'ASSUMPTION', 'Low',
        'Paired with the hydraulic capacity above - they describe the same machine. Mid-range of the Towler & Sinnott high-speed disk correlation (0.26-0.49 m).'),
    'MiscEquip':     (15.0, 'Uncosted equipment allowance', '% of itemised equipment', 103, 'ASSUMPTION', 'Low',
        'A real equipment list runs to hundreds of tags. This covers the small vessels, agitators, blowers, sumps, sampling and packaged units that are not itemised here. Engineering allowance.'),
    'SoftReject':    (0.1, 'Water treatment reject fraction', '-', 104, 'ASSUMPTION', 'Low',
        'Softener / polishing reject as a fraction of raw water intake. Engineering assumption; the treatment plant itself sits inside the OSBL allowance rather than being costed as a separate item.'),
    'CEPCI_B':       (532.9, 'CEPCI - correlation basis (Jan 2010)', '-', 122, 'CITED', 'High',
        'Stated basis of Towler & Sinnott Table 7.2.'),
    'CEPCI_N':       (800.0, 'CEPCI - valuation year', '-', 123, 'PLACEHOLDER', 'Med',
        'Chemical Engineering Plant Cost Index. 2024 monthly values ran 795.4-800.7. The 2025 and 2026 values sit behind the journal paywall; the index hit an all-time high in June 2026, so 800 UNDERSTATES capital. Replace from the journal at your valuation date.'),
    'LOCFAC':        (1.21, 'Location factor, Australia', '-', 124, 'CITED', 'Med',
        'Towler & Sinnott Table 7.7, international location factor for Australia (US Gulf Coast = 1.00). Replaces the 1.25 placeholder carried in v2.x.'),
    'FX':            (1.52, 'USD to AUD exchange rate', 'AUD/USD', 125, 'PLACEHOLDER', 'Med',
        'Set the RBA rate at your valuation date.'),
    'MatFac':        (1.3, 'Material factor, 304 stainless vs carbon steel', '-', 126, 'CITED', 'High',
        'Towler & Sinnott Table 7.6.'),
    'HandPump':      (4.0, 'Hand installation factor - pumps', '-', 127, 'CITED', 'Med',
        'Towler & Sinnott Table 7.4.'),
    'HandVes':       (4.0, 'Hand installation factor - pressure vessels', '-', 128, 'CITED', 'Med',
        'Towler & Sinnott Table 7.4.'),
    'HandHX':        (3.5, 'Hand installation factor - heat exchangers', '-', 129, 'CITED', 'Med',
        'Towler & Sinnott Table 7.4.'),
    'HandMisc':      (2.5, 'Hand installation factor - miscellaneous equipment', '-', 130, 'CITED', 'Med',
        'Towler & Sinnott Table 7.4.'),
    'OSBLPCT':       (0.3, 'OSBL as a fraction of ISBL', '-', 131, 'CITED', 'Med',
        'Towler & Sinnott: 20-50% of ISBL, 30% typical.'),
    'ENGPCT':        (0.3, 'Engineering as a fraction of ISBL + OSBL', '-', 132, 'CITED', 'Med',
        'Towler & Sinnott, typical for a small project.'),
    'CONTPCT':       (0.1, 'Contingency as a fraction of ISBL + OSBL', '-', 133, 'CITED', 'Med',
        'Towler & Sinnott: 10% minimum for a well-defined project. A first-of-a-kind Australian gallium plant arguably warrants 20-30%; carried at 10% and flexed in the tornado.'),
    'WCPCT':         (0.15, 'Working capital as a fraction of annual OPEX', '-', 134, 'CITED', 'Med',
        'Towler & Sinnott: 10-20% typical.'),
    'RESINCAPEX':    (1.0, 'Initial resin charge included in capital', '-', 135, 'ASSUMPTION', 'High',
        '1 = yes (the first fill is capital), 0 = no.'),
    'CAPFAC':        (6.0, 'Equipment-list completeness factor', '-', 136, 'ASSUMPTION', 'Low',
        'READ THIS BEFORE QUOTING A CAPITAL NUMBER. The itemised list on the Equipment sheet covers the major process equipment only. Costed raw it gives an FCI about one sixth of the published Wesselkaemper 2025 comparable and well below the equity already committed to the Alcoa Wagerup project, so the list is incomplete - the correlations are not wrong. Two causes: the Towler vessel correlations explicitly exclude heads, ports and internals, which on a 4.7 m ion exchange column is most of the cost; and the list omits surge tanks, resin traps, backwash, thickening, cake handling, electrolyte filtration, cathode handling, casting, buildings, MCC and control. 6.0 reconciles the bottom-up to the comparable at base conditions. Set to 1.0 to see the raw bottom-up. Reducing this number by completing the equipment list is the highest-value next step on capital.'),
    'CPXMETH':       (2.0, 'Capital method: 1 = raw bottom-up, 2 = bottom-up x completeness factor', '-', 137, 'USER SETTING', 'Med',
        'Method 2 is the base case: it keeps the bottom-up response to liquor throughput but sets the level from a published comparable.'),
    'RefCapex':      (222.0, 'Comparable plant capital cost', 'US$M', 138, 'CITED', 'Med',
        'Wesselkaemper et al. 2025, Bayer-liquor pathway base case, published directly as US$222M in 2024 dollars.'),
    'RefCap':        (76.61, 'Comparable plant capacity', 't Ga/yr', 139, 'CITED', 'Med',
        'Wesselkaemper et al. 2025, same case.'),
    'EXP_CAP':       (0.38146, 'ISBL scaling exponent on liquor flow, first order', '-', 140, 'DERIVED', 'Med',
        'DERIVED, not assumed. The complete bottom-up model was re-run at seven feed assays from 40 to 240 mg/L (liquor flow 202 to 1,211 m3/h) and ln(ISBL/ISBL_base) regressed on ln(Q/Q_base) with a second-order term. Worst-case fit error 2.0% across that whole range, exact at base. Used only by Assay_Curve, Sensitivity and Monte_Carlo so they can run live; CAPEX always uses the full equipment build-up.'),
    'EXP_CAP2':      (0.08612, 'ISBL scaling exponent, second order', '-', 141, 'DERIVED', 'Med',
        'Same fit. Captures the curvature a single power law misses.'),
    'EXP_OPX':       (0.47137, 'Variable operating cost exponent on liquor flow, first order', '-', 142, 'DERIVED', 'Med',
        'DERIVED the same way on the same seven runs. Worst-case fit error 0.22%.'),
    'EXP_OPX2':      (0.11726, 'Variable operating cost exponent, second order', '-', 143, 'DERIVED', 'Med',
        'Same fit.'),
    'ScaleExp':      (0.6, 'Capacity scaling exponent', '-', 144, 'CITED', 'Med',
        'Six-tenths rule; typical range 0.5-0.7 for process plants (Peters, Timmerhaus & West).'),
    'P_ELEC_HI':     (200.0, 'Electricity  (ACTIVE - see section 27)', '$/MWh', 148, 'DERIVED', 'Med',
        'v3.3: this cell is no longer typed. It follows the ACTIVE electricity price at Inputs section 27, which is the base reference A$157/MWh unless the blended-mix selector USEMIX is set to 1. The typed base value now lives at P_ELEC_BASE. Low and high remain the Lu et al. 2026 bounds and are widened automatically on the Monte Carlo sheet if the active price falls outside them.'),
    'P_ELEC_LO':     (92.0, 'Electricity  (ACTIVE - see section 27)', '$/MWh', 148, 'DERIVED', 'Med',
        'v3.3: this cell is no longer typed. It follows the ACTIVE electricity price at Inputs section 27, which is the base reference A$157/MWh unless the blended-mix selector USEMIX is set to 1. The typed base value now lives at P_ELEC_BASE. Low and high remain the Lu et al. 2026 bounds and are widened automatically on the Monte Carlo sheet if the active price falls outside them.'),
    'P_STEAM':       (45.0, 'Steam', '$/t', 149, 'PLACEHOLDER', 'Low',
        'Gas-fired package boiler estimate. Confirm with the host refinery - waste steam may be available.'),
    'P_STEAM_HI':    (70.0, 'Steam', '$/t', 149, 'PLACEHOLDER', 'Low',
        'Gas-fired package boiler estimate. Confirm with the host refinery - waste steam may be available.'),
    'P_STEAM_LO':    (25.0, 'Steam', '$/t', 149, 'PLACEHOLDER', 'Low',
        'Gas-fired package boiler estimate. Confirm with the host refinery - waste steam may be available.'),
    'P_H2SO4':       (250.0, 'H2SO4 (98% w/w, delivered)', '$/t', 150, 'PLACEHOLDER', 'Low',
        'Supplier quote required.'),
    'P_H2SO4_HI':    (400.0, 'H2SO4 (98% w/w, delivered)', '$/t', 150, 'PLACEHOLDER', 'Low',
        'Supplier quote required.'),
    'P_H2SO4_LO':    (150.0, 'H2SO4 (98% w/w, delivered)', '$/t', 150, 'PLACEHOLDER', 'Low',
        'Supplier quote required.'),
    'P_NAOH':        (800.0, 'NaOH (100% basis, delivered)', '$/t', 151, 'PLACEHOLDER', 'Low',
        'Traded as 50% solution, priced here on a dry basis. Supplier quote required.'),
    'P_NAOH_HI':     (1100.0, 'NaOH (100% basis, delivered)', '$/t', 151, 'PLACEHOLDER', 'Low',
        'Traded as 50% solution, priced here on a dry basis. Supplier quote required.'),
    'P_NAOH_LO':     (500.0, 'NaOH (100% basis, delivered)', '$/t', 151, 'PLACEHOLDER', 'Low',
        'Traded as 50% solution, priced here on a dry basis. Supplier quote required.'),
    'P_CAO':         (300.0, 'CaO (quicklime)', '$/t', 152, 'PLACEHOLDER', 'Low',
        'Supplier quote required.'),
    'P_CAO_HI':      (450.0, 'CaO (quicklime)', '$/t', 152, 'PLACEHOLDER', 'Low',
        'Supplier quote required.'),
    'P_CAO_LO':      (200.0, 'CaO (quicklime)', '$/t', 152, 'PLACEHOLDER', 'Low',
        'Supplier quote required.'),
    'P_HCL':         (500.0, 'HCl (100% basis)', '$/t', 153, 'PLACEHOLDER', 'Low',
        'Supplier quote required. Minor line.'),
    'P_HCL_HI':      (800.0, 'HCl (100% basis)', '$/t', 153, 'PLACEHOLDER', 'Low',
        'Supplier quote required. Minor line.'),
    'P_HCL_LO':      (300.0, 'HCl (100% basis)', '$/t', 153, 'PLACEHOLDER', 'Low',
        'Supplier quote required. Minor line.'),
    'P_RESIN':       (15.0, 'Ion exchange resin', '$/kg', 154, 'PLACEHOLDER', 'Low',
        'Vendor quote required (Purolite or equivalent). Sets both the initial charge and the make-up.'),
    'P_RESIN_HI':    (25.0, 'Ion exchange resin', '$/kg', 154, 'PLACEHOLDER', 'Low',
        'Vendor quote required (Purolite or equivalent). Sets both the initial charge and the make-up.'),
    'P_RESIN_LO':    (8.0, 'Ion exchange resin', '$/kg', 154, 'PLACEHOLDER', 'Low',
        'Vendor quote required (Purolite or equivalent). Sets both the initial charge and the make-up.'),
    'P_WATER':       (2.5, 'Process water', '$/kL', 155, 'PLACEHOLDER', 'Low',
        'Co-located refinery supply may be cheaper. Confirm the transfer price with the host.'),
    'P_WATER_HI':    (4.0, 'Process water', '$/kL', 155, 'PLACEHOLDER', 'Low',
        'Co-located refinery supply may be cheaper. Confirm the transfer price with the host.'),
    'P_WATER_LO':    (1.0, 'Process water', '$/kL', 155, 'PLACEHOLDER', 'Low',
        'Co-located refinery supply may be cheaper. Confirm the transfer price with the host.'),
    'P_SALTY':       (20.0, 'Salty water reject disposal', '$/t', 156, 'PLACEHOLDER', 'Low',
        'Depends on integration with the host refinery water balance.'),
    'P_SALTY_HI':    (50.0, 'Salty water reject disposal', '$/t', 156, 'PLACEHOLDER', 'Low',
        'Depends on integration with the host refinery water balance.'),
    'P_SALTY_LO':    (5.0, 'Salty water reject disposal', '$/t', 156, 'PLACEHOLDER', 'Low',
        'Depends on integration with the host refinery water balance.'),
    'P_SOLID':       (150.0, 'Solid residue disposal', '$/t', 157, 'PLACEHOLDER', 'Low',
        'Landfill class to be confirmed.'),
    'P_SOLID_HI':    (300.0, 'Solid residue disposal', '$/t', 157, 'PLACEHOLDER', 'Low',
        'Landfill class to be confirmed.'),
    'P_SOLID_LO':    (50.0, 'Solid residue disposal', '$/t', 157, 'PLACEHOLDER', 'Low',
        'Landfill class to be confirmed.'),
    'P_FEED':        (0.0, 'Spent Bayer liquor feedstock', '$/t', 158, 'ASSUMPTION', 'Med',
        "ASSUMPTION: co-located by-product stream at a zero transfer price. Alcoa state the gallium plant will 'process and return about 10 per cent of its liquor stream', which supports a zero or nominal transfer price. Confirm commercial terms."),
    'P_FEED_HI':     (0.0, 'Spent Bayer liquor feedstock', '$/t', 158, 'ASSUMPTION', 'Med',
        "ASSUMPTION: co-located by-product stream at a zero transfer price. Alcoa state the gallium plant will 'process and return about 10 per cent of its liquor stream', which supports a zero or nominal transfer price. Confirm commercial terms."),
    'P_FEED_LO':     (0.0, 'Spent Bayer liquor feedstock', '$/t', 158, 'ASSUMPTION', 'Med',
        "ASSUMPTION: co-located by-product stream at a zero transfer price. Alcoa state the gallium plant will 'process and return about 10 per cent of its liquor stream', which supports a zero or nominal transfer price. Confirm commercial terms."),
    'P_LABOUR':      (180000.0, 'Operating labour, loaded rate', '$/FTE-yr', 159, 'PLACEHOLDER', 'Med',
        'Australian process-industry loaded rate estimate.'),
    'P_LABOUR_HI':   (220000.0, 'Operating labour, loaded rate', '$/FTE-yr', 159, 'PLACEHOLDER', 'Med',
        'Australian process-industry loaded rate estimate.'),
    'P_LABOUR_LO':   (150000.0, 'Operating labour, loaded rate', '$/FTE-yr', 159, 'PLACEHOLDER', 'Med',
        'Australian process-industry loaded rate estimate.'),
    'N_LABOUR':      (20.0, 'Operator headcount', 'FTE', 160, 'CITED', 'High',
        "Alcoa state the Wagerup gallium plant will create 'about 200 construction and 20 direct operational jobs' (Alcoa Gallium Project factsheet, August 2026). Replaces the v2.x placeholder of 16."),
    'N_LABOUR_HI':   (26.0, 'Operator headcount', 'FTE', 160, 'CITED', 'High',
        "Alcoa state the Wagerup gallium plant will create 'about 200 construction and 20 direct operational jobs' (Alcoa Gallium Project factsheet, August 2026). Replaces the v2.x placeholder of 16."),
    'N_LABOUR_LO':   (16.0, 'Operator headcount', 'FTE', 160, 'CITED', 'High',
        "Alcoa state the Wagerup gallium plant will create 'about 200 construction and 20 direct operational jobs' (Alcoa Gallium Project factsheet, August 2026). Replaces the v2.x placeholder of 16."),
    'F_MAINT':       (0.03, 'Maintenance', '% of ISBL /yr', 161, 'CITED', 'Med',
        'Towler & Sinnott / Peters, Timmerhaus & West typical factor.'),
    'F_MAINT_HI':    (0.05, 'Maintenance', '% of ISBL /yr', 161, 'CITED', 'Med',
        'Towler & Sinnott / Peters, Timmerhaus & West typical factor.'),
    'F_MAINT_LO':    (0.02, 'Maintenance', '% of ISBL /yr', 161, 'CITED', 'Med',
        'Towler & Sinnott / Peters, Timmerhaus & West typical factor.'),
    'F_INS':         (0.015, 'Insurance, rates and admin', '% of ISBL /yr', 162, 'CITED', 'Med',
        'Typical TEA factor.'),
    'F_INS_HI':      (0.02, 'Insurance, rates and admin', '% of ISBL /yr', 162, 'CITED', 'Med',
        'Typical TEA factor.'),
    'F_INS_LO':      (0.01, 'Insurance, rates and admin', '% of ISBL /yr', 162, 'CITED', 'Med',
        'Typical TEA factor.'),
    'F_OVER':        (0.6, 'Plant overhead', '% of labour + maintenance', 163, 'CITED', 'Med',
        'Towler & Sinnott: 50-100% of labour plus maintenance; 60% used.'),
    'F_OVER_HI':     (0.8, 'Plant overhead', '% of labour + maintenance', 163, 'CITED', 'Med',
        'Towler & Sinnott: 50-100% of labour plus maintenance; 60% used.'),
    'F_OVER_LO':     (0.4, 'Plant overhead', '% of labour + maintenance', 163, 'CITED', 'Med',
        'Towler & Sinnott: 50-100% of labour plus maintenance; 60% used.'),
    'TAXR':          (0.3, 'Corporate tax rate', '-', 167, 'CITED', 'High',
        'ATO - Australian company tax rate for a large business.'),
    'INFL':          (0.025, 'Expected inflation (CPI)', '-', 169, 'PLACEHOLDER', 'Low',
        'RBA target band midpoint. Used ONLY to express the nominal tax depreciation deduction in constant dollars; no cash flow is escalated.'),
    'SALV':          (0.0, 'Salvage value at end of life', 'AUD', 170, 'ASSUMPTION', 'Med',
        'Default zero, treated pre-tax.'),
    'CONSTR':        (1.0, 'Construction period', 'yr', 171, 'ASSUMPTION', 'Med',
        'All capital in Year 0. Alcoa report about 200 construction jobs.'),
    'BM_CHINA':      (247.0, 'China ex-works, 4N', 'USD/kg 4N', 175, 'CITED', 'Med',
        'galliumprice.com market data, 3 March 2026 (about CNY 1,805/kg).'),
    'BM_EUCIF':      (1375.0, 'Europe CIF main airport, 4N', 'USD/kg 4N', 176, 'CITED', 'Med',
        'galliumprice.com, March 2026: quoted range USD 1,300-1,450/kg. Midpoint used.'),
    'BM_ROTT':       (2102.0, 'Rotterdam in-warehouse, 4N', 'USD/kg 4N', 177, 'CITED', 'Med',
        'galliumprice.com, 3 March 2026: USD 2,101.60/kg, up 123% over twelve months. The spread to the Chinese domestic price is the export-control premium, not logistics.'),
    'BM_WESS':       (422.0, 'Wesselkaemper et al. 2025, US Bayer pathway LCOP', 'USD/kg 4N', 178, 'CITED', 'Med',
        'Published levelised cost for a 76.61 t/yr US Bayer-liquor plant, 2024 USD.'),
    'POLSEL':        (1.0, 'ACTIVE POLICY PACKAGE  (1-4)', '-', 204, 'USER SETTING', 'High',
        '=INDEX($B$207:$B$210,POLSEL)'),
    'WACCMODE':      (2.0, 'Discount-rate mode: 1 = legacy 7% real reference, 2 = component CAPM/WACC', '-', 222, 'USER SETTING', 'High',
        'Mode 1 reproduces the v3.0 deterministic result and exists only as a regression reference. Mode 2 is the basis for all policy analysis.'),
    'R_WACC_LEG':    (0.07, 'Legacy real WACC (v3.0 reference only)', '-', 223, 'PLACEHOLDER', 'Low',
        'The single typed real WACC carried in v3.0. Retained unchanged so the original result can be reproduced. It was a PLACEHOLDER then and remains one.'),
    'PSTAR_V30':     (737.90939087957, 'v3.0 regression reference p*', 'AUD/kg', 224, 'REFERENCE', 'High',
        'The deterministic p* the v3.0 workbook produced with a typed 7% real WACC and no policy support. Stored so the Checks sheet can prove this workbook still reproduces it. Do not edit.'),
    'RFR':           (0.052, 'Risk-free rate (nominal, 10-year AGS)', '-', 225, 'CITED', 'Med',
        'Australian 10-year government bond yield 5.20% on 8 September 2026 (Trading Economics), near its highest since mid-2011. Update at your valuation date - this is a spot rate and it is currently elevated.'),
    'MRP':           (0.062, 'Market risk premium', '-', 226, 'CITED', 'Med',
        'Australian Energy Regulator, Rate of Return annual update November 2025: MRP 6.2%, a fixed parameter of the 2022 Rate of Return Instrument. The most authoritative regularly-published Australian MRP estimate.'),
    'BETA_U':        (1.05, 'Unlevered (asset) beta', '-', 227, 'CITED', 'Med',
        'Damodaran global industry betas, data as of January 2026: Metals & Mining unlevered beta 1.05 across 1,874 firms. Chemical (Basic) is 0.91 and Chemical (Specialty) 0.98 - a gallium refinery arguably sits between mining and specialty chemicals, so 1.05 is the conservative end.'),
    'GEAR':          (0.4, 'Target debt share of net funding requirement', '-', 228, 'ASSUMPTION', 'Low',
        'Project-finance gearing for a first-of-a-kind critical minerals plant. Lower than the 60% the AER uses for regulated networks because the revenue is merchant and the technology is unproven at this scale. ILLUSTRATIVE.'),
    'KD_MARGIN':     (0.04, 'Commercial credit margin', '-', 230, 'ASSUMPTION', 'Low',
        'Illustrative project-finance margin for a first-of-a-kind critical minerals processing plant with merchant price exposure. NOT sourced from a transaction - no comparable Australian gallium project financing has been publicly priced.'),
    'KD_FEES':       (0.0025, 'Commercial fees, amortised to an annual rate', '-', 231, 'ASSUMPTION', 'Low',
        'Establishment, commitment and agency fees expressed as an equivalent annual margin. Illustrative.'),
    'KD_CONC':       (0.0685, 'Government-supported borrowing rate (all-in nominal)', '-', 232, 'ASSUMPTION', 'Low',
        'ILLUSTRATIVE. Export Finance Australia publishes NO interest rate, margin or tenor for its $5bn Critical Minerals Facility. The Arafura Nolans announcement of 21 October 2025 discloses facility sizes (EFA up to US$100M equity; US$533M debt from Australian Government agencies) but explicitly leaves pricing to due diligence and definitive documentation. Do not represent this rate as a government offer.'),
    'TENOR':         (15.0, 'Concessional loan tenor', 'yr', 233, 'ASSUMPTION', 'Low',
        'Illustrative. The concession is FINITE and the project life is 30 years - applying it across the full life would overstate the benefit, which is why FINMODE 2 is the default.'),
    'REPAY':         (1.0, 'Repayment profile: 1 = straight-line amortising, 2 = bullet at maturity', '-', 234, 'ASSUMPTION', 'Low',
        'Straight-line amortisation over the tenor is the conservative default; bullet keeps the full balance outstanding and roughly doubles the concession value.'),
    'FINMODE':       (2.0, 'Financing valuation: 1 = concession inside WACC, 2 = explicit financing benefit (APV)', '-', 235, 'USER SETTING', 'High',
        'Mode 2 is the DEFAULT and the defensible treatment for a finite concessional loan: WACC uses the commercial cost of debt only, and the concession is valued separately as the present value of after-tax interest savings over the actual tenor. Mode 1 blends the concessional rate into Kd for the whole 30-year life, which over-credits a 15-year loan. The two are mutually exclusive - the benefit is never counted twice, and a check on the Checks sheet enforces it.'),
    'CMPTI_RATE_STAT': (0.1, 'CMPTI offset rate (statutory)', '-', 244, 'STATUTORY', 'High',
        'Critical Minerals Production Tax Incentive: a refundable tax offset of 10 per cent of eligible processing expenditure (ATO, Critical Minerals Production Tax Incentive; Dept of Industry, Science and Resources).'),
    'CMPTI_MAXYRS':  (10.0, 'Maximum claim years per registered activity', 'yr', 245, 'STATUTORY', 'High',
        'A company may register for up to 10 years (ATO / DISR).'),
    'CMPTI_FY_OPEN': (2027.0, 'First income year the offset is available (calendar year the income year starts)', '-', 246, 'STATUTORY', 'High',
        'The offset applies to income years starting on or after 1 July 2027 (ATO). 2027 here means the 2027-28 income year.'),
    'CMPTI_FY_CLOSE': (2039.0, 'Last income year the offset is available (calendar year the income year starts)', '-', 247, 'STATUTORY', 'High',
        'Income years ending on or before 30 June 2040 (ATO), i.e. the 2039-40 income year is the last.'),
    'CONSTR_FY':     (2027.0, 'Income year of construction (model year 0)', '-', 248, 'ASSUMPTION', 'Med',
        'Calendar year in which the construction income year begins. Model year 0 = the 2027-28 income year.'),
    'OPS_FY1':       (2028.0, 'Income year of first production (model year 1)', '-', 249, 'ASSUMPTION', 'Med',
        'Model year 1 = the 2028-29 income year. One-year construction, consistent with the v3.0 convention.'),
    'CMPTI_REG_FY':  (2028.0, 'First income year claimed (registration)', '-', 250, 'ASSUMPTION', 'Med',
        'Assumed to coincide with first production. Registration must precede a claim (ATO); no processing expenditure arises before production.'),
    'CMPTI_LAG':     (0.0, 'Receipt lag, years', 'yr', 251, 'SIMPLIFICATION', 'Med',
        'SIMPLIFICATION, clearly labelled: the refundable offset is modelled as received in the same model year the expenditure is incurred. In practice it is claimed in the company tax return for that income year and refunded after lodgement, so real receipt lags by roughly one year. Set to 1 to test that.'),
    'GRANT_YR':      (0.0, 'Model year the grant is received', 'yr', 282, 'ASSUMPTION', 'Med',
        'Received on financial close, alongside the capital spend. Set later to test staged milestone payments.'),
    'GRANT_ASSESS':  (1.0, 'Grant assessable as income when received (1 = yes)', '-', 283, 'CITED (case law)', 'Med',
        'DEFAULT SET FROM CASE LAW. In Denmark Community Windfarm Ltd v FCT the Full Federal Court held that a Commonwealth grant covering 50% of wind turbine construction cost was an assessable recoupment under Subdivision 20-A of the ITAA 1997: the grant indemnified the taxpayer against expenditure for which Division 40 decline-in-value deductions were available. A capital grant toward a processing plant is closely analogous. This is the conservative and evidence-based convention, but it is not a ruling on THIS grant - obtain a private ruling before relying on it.'),
    'GRANT_REDBASE': (0.0, 'Grant reduces the depreciable base (1 = yes)', '-', 284, 'CITED (case law)', 'Med',
        'Set to 0 because in Denmark the grant was assessable AND depreciation continued on the full asset cost - the Court noted precisely that timing mismatch. Setting both this and GRANT_ASSESS to 1 would double-count the clawback. The alternative convention (grant not assessable, base reduced) is available by setting GRANT_ASSESS = 0 and this = 1, and is exposed in the tornado.'),
    'OT_COV':        (1.0, 'Contract coverage, share of annual output', '-', 340, 'USER SETTING', 'High',
        'Fraction of production sold under the offtake. The remainder is sold merchant.'),
    'OT_DUR':        (30.0, 'Contract duration', 'yr', 341, 'USER SETTING', 'High',
        'Years from first production. Equal to the plant life gives a full-horizon contract.'),
    'OT_IDX':        (1.0, 'Contract price indexed to CPI (1 = yes)', '-', 342, 'USER SETTING', 'High',
        'The model is in constant 2026 AUD. A fully CPI-indexed contract is a constant REAL price. A fixed nominal price loses real value at the inflation rate, which this switch models.'),
    'RESINSEL':      (1.0, 'RESIN PRESET SELECTOR', '1-4', 349, 'SELECTOR', '-',
        '1 = TY-CH550 base case (v3.0/v3.1 default)   2 = amidoxime chelating resin   3 = high working capacity variant   4 = custom, typed below.'),
    'EF_ELEC':       (0.5, 'Grid electricity, scope 2 (WA SWIS)', 'kg CO2e / kWh', 367, 'CITED', 'High',
        'Australian National Greenhouse Accounts Factors 2025 (DCCEEW), location-based scope 2 factor for the Western Australian SWIS grid. WA is the right grid for a Wagerup or Worsley host. Substitute the Queensland factor for a QAL or Yarwun host. Verify the table number in the DCCEEW PDF before citing in the thesis.'),
    'EF_ELEC_S3':    (0.06, 'Grid electricity, scope 3 (transmission and distribution losses)', 'kg CO2e / kWh', 368, 'CITED', 'High',
        'NGA Factors 2025, WA SWIS. Reported separately under scope 3 and NOT added to the scope 2 figure. Included on the Carbon sheet as a separate line so the boundary is explicit.'),
    'EF_GAS':        (51.53, 'Natural gas combustion, scope 1', 'kg CO2e / GJ', 369, 'CITED', 'Med',
        'Australian NGA Factors, natural gas distributed in a pipeline, full scope 1 combustion factor. Used only to derive the steam factor below.'),
    'BOILEFF':       (0.85, 'Boiler thermal efficiency', '-', 370, 'ASSUMPTION', 'Med',
        'Gas-fired package boiler, higher heating value basis. Engineering assumption.'),
    'EF_NAOH':       (1.12, 'Sodium hydroxide, embodied', 'kg CO2e / kg', 372, 'PLACEHOLDER', 'Low',
        'Chlor-alkali membrane route, mass allocation across Cl2 / NaOH / H2. The published range is roughly 0.6 to 1.9 depending ENTIRELY on the allocation method, which must be recorded alongside any number quoted. A value near 1.2 is what reconciles the Luo et al. 2025 totals - see the Carbon sheet benchmark block.'),
    'EF_H2SO4':      (0.12, 'Sulfuric acid 98%, embodied', 'kg CO2e / kg', 373, 'PLACEHOLDER', 'Low',
        'Contact process, ecoinvent-class proxy. Not verified against a licensed dataset.'),
    'EF_CAO':        (1.1, 'Quicklime, embodied', 'kg CO2e / kg', 374, 'PLACEHOLDER', 'Low',
        'Calcination CO2 plus kiln fuel. Proxy. Not verified against a licensed dataset.'),
    'EF_HCL':        (0.9, 'Hydrochloric acid, embodied', 'kg CO2e / kg', 375, 'PLACEHOLDER', 'Low',
        'Proxy. Minor line at 0.012 kg/kg Ga - it cannot move the answer.'),
    'EF_RESIN':      (6.0, 'Ion exchange resin, embodied', 'kg CO2e / kg', 376, 'PLACEHOLDER', 'Low',
        'Polymer proxy. Luo et al. used ecoinvent cationic resin as a stand-in for chelating resin and said so. A resin-specific LCI from the vendor would replace this.'),
    'EF_WATER':      (0.0003, 'Fresh water supply, embodied', 'kg CO2e / kg', 377, 'PLACEHOLDER', 'Low',
        'Treatment plus pumping, about 0.3 kg CO2e per kL. Proxy.'),
    'EF_REJECT':     (0.001, 'Water treatment reject disposal', 'kg CO2e / kg', 378, 'PLACEHOLDER', 'Low',
        'Handling and transport allowance. Proxy.'),
    'EF_SOLID':      (0.02, 'Solid residue disposal', 'kg CO2e / kg', 379, 'PLACEHOLDER', 'Low',
        'Landfill handling allowance. Proxy.'),
    'EF_FEED':       (0.0, 'Bayer liquor slipstream', 'kg CO2e / kg liquor', 380, 'ASSUMPTION', 'Med',
        'ZERO by cut-off. The slipstream is drawn from and returned to an existing refinery circuit that would run anyway, so no upstream alumina burden is allocated to it. This is the same convention as the zero transfer price on the cost side, and it is a CHOICE - an economic-allocation study would load part of the refinery burden onto the gallium and the number would not be small.'),
    'EF_NA2SO4':     (0.0, 'Sodium sulfate returned to the refinery circuit', 'kg CO2e / kg', 381, 'ASSUMPTION', 'Med',
        'No avoided-burden credit taken for the Na2SO4 returned to the host liquor. Conservative and deliberate. Changing it to a negative number would credit the project for a co-product it does not sell.'),
    'LUO_EF_ELEC':   (1.16, 'Luo et al. grid factor (benchmark only)', 'kg CO2e / kWh', 382, 'CITED', 'High',
        "Luo et al. 2025, Int. J. LCA 30:1545-1559, section 3.1: 'the carbon intensity for electricity is 1.16 CO2-eq/kWh', a Chinese coal-dominated grid (>96% hard coal). Used ONLY in the benchmark block on the Carbon sheet. It never touches this plant."),
    'LUO_ELEC':      (102.28, 'Luo et al. total electricity (benchmark only)', 'kWh / kg Ga', 383, 'CITED', 'High',
        'Luo et al. 2025 Table 1, total electricity for 1 kg of 4N gallium.'),
    'LUO_GWP':       (282.0, 'Luo et al. global warming result (benchmark only)', 'kg CO2e / kg Ga', 384, 'DERIVED - see note', 'Med',
        "RECONSTRUCTED. Luo Table 2 prints 2.82 x 10^-2 kg CO2-eq, which cannot be right: their own electricity line alone is 102.28 kWh x 1.16 = 118.6 kg CO2e. Reading the exponent as +2 gives 282, which puts electricity at 42.1% of the total and matches their statement that electricity is 'over 40% of GHG emissions' (section 3.1). The published exponent is wrong. See the Carbon sheet for the arithmetic."),
    'AL_LIQ1':       (0.5, 'Liquor circuit pumping power to UP1 (filter press)', '-', 390, 'ASSUMPTION', 'Low',
        'PumpHead is a single lumped 40 m covering slipstream take-off, the filter press pressure drop, the ion exchange bed pressure drop and the return to circuit. It cannot be split without a hydraulic model. A plate-and-frame filter can run several bar, a resin bed at 20 m/h runs well under one bar, but the take-off and return piping serves both. 0.50 is a stated split, not a measurement. The remainder goes to UP2. Changing it moves cost and carbon between two bars on a chart and changes no total anywhere in the model.'),
    'ACCU':          (36.28, 'Australian Carbon Credit Unit, generic spot', 'AUD / t CO2e', 401, 'UNUSED', 'Med',
        'RETAINED FOR CONTEXT, USED IN NO CALCULATION. v3.3 removed the implied carbon-cost line from the Carbon sheet: the energy-mix module deliberately excludes carbon prices and emissions credits. Generic ACCU spot price A$36.28/t as at 31 March 2026, Clean Energy Regulator Quarterly Carbon Market Report, March quarter 2026.'),
    'MIX_GRID':      (1.0, 'Grid electricity', '-', 408, 'SELECTOR', '-',
        'Purchased from the network. Default is 100% grid, which reproduces the v3.2 workbook exactly.'),
    'MIX_SOLAR':     (0.0, 'Direct behind-the-meter solar', '-', 409, 'SELECTOR', '-',
        'Generated on site and consumed directly, without passing through storage. No network charges, no scope 2 - it is not purchased electricity.'),
    'MIX_SOLBAT':    (0.0, 'Solar through battery storage', '-', 410, 'SELECTOR', '-',
        'Solar electricity that has been through the battery. The battery is MODELLED AS SOLAR-CHARGED STORAGE, not as a generation source: its charging energy is solar, grossed up for round-trip losses below.'),
    'MIX_WIND':      (0.0, 'Dedicated direct-connected wind', '-', 411, 'SELECTOR', '-',
        'A direct physical connection to a dedicated wind asset. NOT a grid-delivered PPA and NOT a renewable certificate surrender - those would leave the physical scope 2 factor unchanged under a location-based method and are outside this module.'),
    'MIX_GAS':       (0.0, 'Onsite natural-gas generation', '-', 412, 'SELECTOR', '-',
        'Reciprocating gas engines or similar on site. This is the only route that creates scope 1 emissions at the plant boundary. No cogeneration or heat-recovery credit is taken.'),
    'PE_SOLAR':      (75.0, 'Direct behind-the-meter solar, delivered', 'AUD / MWh', 423, 'ESTIMATE', 'Low',
        'ESTIMATE. Lu et al. 2026 put onsite PV PLUS battery at about A$92/MWh, so PV alone consumed directly must sit below that. A$75/MWh is carried as a central estimate. It is not a quoted tariff and there is no Australian published delivered price for behind-the-meter industrial solar that this model can cite.'),
    'PE_WIND':       (85.0, 'Dedicated direct-connected wind, delivered', 'AUD / MWh', 424, 'ESTIMATE', 'Low',
        'ESTIMATE. CSIRO GenCost 2025-26 reports the average NEM generation price at about A$104/MWh in 2025 with electricity futures implying A$80-90/MWh by 2030. A dedicated direct-connected wind supply is priced here inside that band. GenCost publishes LCOE, which is a busbar number and NOT a delivered tariff; this figure is an estimate that spans that gap without a source for the difference.'),
    'GASPRICE':      (10.0, 'Natural gas, delivered to site', 'AUD / GJ', 425, 'ESTIMATE', 'Low',
        'ESTIMATE anchored on IEEFA (November 2025): Western Australian domestic gas CONTRACT prices about A$7/GJ and SPOT about A$9/GJ in 2023-24. A$10/GJ carries a real escalation to 2026 that is NOT sourced. WA domestic gas is subject to a reservation policy and an east-coast host would face a different market.'),
    'GENEFF':        (0.38, 'Onsite gas generator electrical efficiency', '-', 426, 'ASSUMPTION', 'Med',
        'Reciprocating gas engine, sent-out basis, consistent with the higher-heating-value energy content used by the NGA factors. Engineering assumption. Used ONCE, to convert fuel to delivered electricity in both the price and the emission factor below.'),
    'GENOM':         (15.0, 'Onsite gas generation, non-fuel operating cost', 'AUD / MWh', 427, 'ESTIMATE', 'Low',
        'Maintenance, overhaul reserve and lubricants. Excludes all capital. ESTIMATE.'),
    'RTE':           (0.88, 'Battery round-trip efficiency', '-', 432, 'CITED (range)', 'Med',
        'Utility-scale lithium-ion round-trip efficiency is typically 85-90% (Global Journal of Engineering and Technology Advances, 2025 review of utility-scale LIB LCA). 88% is the midpoint. Must be greater than zero and no more than 100%.'),
    'BATT_CAPEX':    (300.0, 'Battery capital cost', 'AUD / kWh capacity', 433, 'CITED (range)', 'Med',
        'CSIRO GenCost 2025-26 gives about A$200-400/kWh for two-hour large-scale battery storage in 2025-26 dollars. A$300/kWh is the midpoint. Used ONLY to derive a storage cost per MWh discharged - no battery capital is added to the plant CAPEX anywhere.'),
    'BATT_CYC':      (5000.0, 'Battery cycle life', 'cycles', 434, 'CITED (range)', 'Low',
        'Lithium iron phosphate cells are reported at 4,000-6,000 cycles for utility-scale duty (GJETA 2025 review). 5,000 is the midpoint. Utility duty is also reported to accelerate capacity fade, so this is optimistic.'),
    'BATT_DOD':      (0.9, 'Usable depth of discharge', '-', 435, 'ASSUMPTION', 'Med',
        'Fraction of nameplate capacity cycled. Engineering assumption.'),
    'BATT_MFG':      (100.0, 'Battery manufacturing emissions', 'kg CO2e / kWh capacity', 436, 'CITED (range)', 'Low',
        'Production-phase emissions for utility-scale lithium-ion are reported at 50-150 kg CO2e per kWh of installed capacity (GJETA 2025 review). 100 is the midpoint. This is a CAPACITY figure and must be spread over lifetime throughput before it can be used per kWh discharged.'),
    'EFG_S1':        (0.0, 'Grid, scope 1', 'kg CO2e / kWh', 442, 'BY DEFINITION', 'High',
        'ZERO BY DEFINITION, not by omission. Grid electricity is purchased, so its combustion emissions belong to the generator and are reported by the buyer as scope 2.'),
    'EFS_S1':        (0.0, 'Direct solar, scope 1', 'kg CO2e / kWh', 445, 'BY DEFINITION', 'High',
        'No combustion.'),
    'EFS_S2':        (0.0, 'Direct solar, scope 2', 'kg CO2e / kWh', 446, 'BY DEFINITION', 'High',
        'Not purchased electricity, so no scope 2 under either the location-based or the market-based method.'),
    'EFS_UP':        (0.04, 'Direct solar, embodied', 'kg CO2e / kWh', 447, 'ESTIMATE', 'Low',
        'ESTIMATE. Published life cycle intensities for utility-scale photovoltaics span 18-180 g CO2e/kWh, with manufacturing responsible for 70-90% of the total (Energies 2025, 18(24):6413 review of 2015-2025 LCAs). 40 g/kWh is carried as a central estimate for a modern installation. It is NOT zero and must not be treated as zero.'),
    'EFW_S1':        (0.0, 'Direct wind, scope 1', 'kg CO2e / kWh', 448, 'BY DEFINITION', 'High',
        'No combustion.'),
    'EFW_S2':        (0.0, 'Direct wind, scope 2', 'kg CO2e / kWh', 449, 'BY DEFINITION', 'High',
        'Direct-connected, not purchased from the network.'),
    'EFW_UP':        (0.012, 'Direct wind, embodied', 'kg CO2e / kWh', 450, 'ESTIMATE', 'Med',
        'ESTIMATE inside a cited range. Published onshore wind life cycle intensities span 7-56 g CO2e/kWh with modern installations clustering at 10-15 g (Energies 2025, 18(24):6413). Steel and other materials are 80-90% of it. 12 g/kWh is carried.'),
    'EFB_S1':        (0.0, 'Solar via battery, scope 1', 'kg CO2e / kWh', 451, 'BY DEFINITION', 'High',
        'No combustion.'),
    'EFB_S2':        (0.0, 'Solar via battery, scope 2', 'kg CO2e / kWh', 452, 'BY DEFINITION', 'High',
        'Charging energy is solar, which is not purchased.'),
    'EFGAS_S2':      (0.0, 'Onsite gas, scope 2', 'kg CO2e / kWh', 455, 'BY DEFINITION', 'High',
        'Self-generated, not purchased.'),
    'GAS_S3_GJ':     (4.0, 'Natural gas, scope 3 upstream', 'kg CO2e / GJ', 456, 'CITED', 'High',
        'NGA Factors 2025 Table 6, Western Australia non-metropolitan: 4.0 kg CO2e/GJ for extraction, processing and transmission. WA metropolitan is 4.1; New South Wales is 13.1-14.0, so a different host state changes this materially.'),
    'USEMIX':        (0.0, 'Use blended electricity price in the financial model?', '-', 463, 'SELECTOR', '-',
        '0 = No (default). 1 = Yes. In mode 1 the electricity unit price becomes the blended price; nothing else in the financial or policy logic changes.'),
    'P_ELEC_BASE':   (157.0, 'Electricity price, base reference', 'AUD / MWh', 464, 'CITED (range)', 'Med',
        'The typed value that was at Inputs section 10 in v3.2, moved here so it stays an independent reference that mode 1 cannot overwrite. Lu et al. 2026 (Solar Energy 303): onsite PV+BESS about A$92/MWh at the low end, Australian industrial grid tariffs to A$200/MWh at the high end.'),

    # ---- added in V3: aligned with OpenGa_v3.5_MEB.xlsx sections 29, 30 and 31 ----
    'SSCap':            (100.0, 'UP1 suspended solids captured in the cake', '%', 481, 'ASSUMPTION', 'Med',
        'All suspended solids report to the filter cake. Polishing duty on an already-clarified liquor (R9).'),
    'EluAl':            (100.0, 'UP5 Al eluted from the resin', '%', 482, 'ASSUMPTION', 'Low',
        'All co-adsorbed Al is assumed to elute and precipitate with the gallium - the same assumption already stated at MEB row 94 (R9).'),
    'EluV':             (0.0, 'UP5 V eluted from the resin', '%', 483, 'ASSUMPTION', 'Low',
        'V is assumed to stay on the resin through acid elution and to leave at regeneration. UNVERIFIED - element-specific elution data is a Priority-1 gap.'),
    'MistFrac':         (1.2285714285714286e-05, 'UP4 acid mist per kg delivered acid', 'kg/kg', 484, 'CITED', 'Med',
        'Luo et al. 2025 Table 1 report G1 acid mist 6.88e-4 kg per kg Ga against a 56 kg delivered acid dose. Negligible but carried so the acid ledger closes.'),
    'EWRecycle':        (0.0, 'UP10 spent electrolyte returned to UP9', '%', 485, 'SELECTOR', '-',
        'ZERO = once-through electrolyte, which is what Luo et al. 2025 describe: their W6 is neutralised with the refining effluent and discarded. Above zero the UP9-UP10 loop is solved algebraically and S30 splits into S30R and S30P. OPEX still buys NaOH_UP9 in full.'),
    'MO2':              (31.998, 'M(O2)', 'g/mol', 486, 'CITED', 'High',
        'CRC physical constants (R11).'),
    'MH2':              (2.016, 'M(H2)', 'g/mol', 487, 'CITED', 'High',
        'CRC physical constants (R11).'),
    'ResinMode':        (1.0, 'Resin life basis: 1 = calendar years, 2 = loading cycles', '-', 495, 'USER SETTING', '-',
        'v3.4 amortises the resin charge over ResinLife calendar years. The cited source reports a life in CYCLES, roughly 30. At the modelled cycle time the two are not the same statement. Mode 1 is the v3.4 behaviour and is the default so nothing moves silently.'),
    'ResinCycles':      (30.0, 'Resin service life in loading cycles', 'cycles', 496, 'CITED', 'Med',
        'Luo et al. 2025 state the chelating resins are designed to be reused for around 30 cycles before disposal (R1).'),
    'BurdenV':          (1.0, 'V burden on resin capacity', 'kg Ga-equiv/kg V', 497, 'ASSUMPTION', 'Low',
        'v3.4 charges vanadium against the Ga-basis capacity at 1:1, which this reproduces. The true multicomponent working capacity is unmeasured.'),
    'BurdenAl':         (0.0, 'Al burden on resin capacity', 'kg Ga-equiv/kg Al', 498, 'ASSUMPTION', 'Low',
        'v3.4 EXCLUDES aluminium from the capacity calculation because co-adsorption is only 0.1%. But 0.1% of a 50 g/L liquor is 2.77 kg Al per kg Ga - more than twice the gallium loaded. Zero and one are both assumptions; zero is the aggressive one. Priority-1 measurement.'),
    'RetainLiq':        (0.0, 'Liquid retained in the resin bed', 'L liquid/L bed', 499, 'ASSUMPTION', 'Low',
        'v3.4 does not quantify interstitial liquor, so S5/S8 carry no liquid and S7 carries no displaced liquor. Above zero the streams pick it up.'),
    'AlRemUP9':         (100.0, 'Al rejected to the purification cake at UP9', '%', 500, 'ASSUMPTION', 'Low',
        'v3.4 assumes PERFECT aluminium rejection, which is what makes the electrolyte look clean. A second independently built MEB assumes 99% and lands at 0.996 g Al/L against its own 1 g/L screening limit.'),
    'CakeLiqSol':       (0.0, 'Mother-liquor solutes carried in the cake moisture', 'fraction', 501, 'ASSUMPTION', 'Low',
        '0 = cake moisture is pure water (the v3.4 convention). 1 = it carries dissolved Na2SO4 at the mother-liquor composition, which is the physically correct statement and is what puts sulfate into the electrolyte.'),
    'LimAlEW':          (1.0, 'Electrolyte screening limit, Al', 'g Al/L', 502, 'PLACEHOLDER', 'Low',
        'No published limit for Al in gallium electrowinning was located. Treat as a placeholder that forces the question.'),
    'LimSO4EW':         (30.0, 'Electrolyte screening limit, Na2SO4', 'g/L', 503, 'PLACEHOLDER', 'Low',
        'PLACEHOLDER - no published limit located.'),
    'LimVEW':           (1.0, 'Electrolyte screening limit, V', 'g V/L', 504, 'PLACEHOLDER', 'Low',
        'Vanadium is reported to lower the hydrogen overvoltage and to deposit at the cathode, requiring purification before electrolysis (R3). The numeric limit is a placeholder.'),
    'MNa':              (22.99, 'M(Na)', 'g/mol', 505, 'CITED', 'High',
        'CRC / CIAAW abridged standard atomic weights (R11).'),
    'MS':               (32.06, 'M(S)', 'g/mol', 506, 'CITED', 'High',
        'CRC / CIAAW (R11).'),
    'MCl':              (35.45, 'M(Cl)', 'g/mol', 507, 'CITED', 'High',
        'CRC / CIAAW (R11).'),
    'MCa':              (40.078, 'M(Ca)', 'g/mol', 508, 'CITED', 'High',
        'CRC / CIAAW (R11).'),
    'MV':               (50.942, 'M(V)', 'g/mol', 509, 'CITED', 'High',
        'CRC / CIAAW (R11).'),
    'T_HOST':           (52.0, 'Host liquor at the tie-in', 'degC', 515, 'CITED', 'Med',
        'ICSOBA 2022 (AA30): spent liquor is available at 50-55 degC at operating conditions. Midpoint carried.'),
    'T_AMB':            (25.0, 'Fresh reagents and raw water', 'degC', 516, 'ASSUMPTION', 'Med',
        'Ambient supply. Engineering assumption.'),
    'T_IX':             (52.0, 'Adsorption and washing', 'degC', 517, 'ASSUMPTION', 'Med',
        'No cooling of the host liquor is modelled: Luo et al. 2025 place their cooling on the desorption circuit, not the feed.'),
    'T_ELU':            (50.0, 'Elution outlet', 'degC', 518, 'ASSUMPTION', 'Low',
        'Luo et al. 2025 carry a 290 kW cooling unit on this circuit, so it is temperature-controlled. The set point is not published.'),
    'T_PREC':           (40.0, 'Precipitation and centrifuge', 'degC', 519, 'ASSUMPTION', 'Low',
        'Engineering assumption.'),
    'T_PUR':            (100.0, 'Purification', 'degC', 520, 'CITED', 'Med',
        'Luo et al. 2025: the gallium-rich sludge is dissolved and heated to 100 degC using exhausted steam from the evaporator station.'),
    'T_EW':             (60.0, 'Electrowinning', 'degC', 521, 'ASSUMPTION', 'Low',
        'Engineering assumption.'),
    'T_REF':            (40.0, 'Refining outlet', 'degC', 522, 'ASSUMPTION', 'Low',
        'Engineering assumption.'),
    'CP_W':             (4.18, 'Liquid water heat capacity', 'kJ/kg/K', 523, 'CITED', 'High',
        'Standard value near ambient (R11).'),
    'CP_NW':            (1.5, 'Apparent non-water component heat capacity', 'kJ/kg/K', 524, 'PLACEHOLDER', 'Low',
        'SCREENING VALUE. SysCAD implements published Bayer-liquor correlations but has no gallate species at all, so no property basis exists for the Ga-bearing streams. Replace before quoting any thermal number.'),
    'CP_LIQ':           (3.4, 'Bayer liquor balance heat capacity', 'kJ/kg/K', 525, 'PLACEHOLDER', 'Low',
        'SCREENING VALUE for the unspeciated liquor row. Published correlations exist (LM_1985, Mulloy-Donaldson). Water is 4.18; concentrated Bayer liquor is lower.'),
}
